### PR TITLE
Include split level in filenames

### PR DESCRIPTION
**Pull request by wddgit**
See PR cms-sw/cmssw#46044 for a description. This PR should be merged together with that one or the related unit test will fail. The PR test for that other PR tests this one.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
I'd think we wouldn't need to test these data PRs individually, and one joint test with https://github.com/cms-sw/cmssw/pull/46044 would be enough.

**Comment by wddgit** [comment]
abort test

I agree. The test with the main cmssw PR is all that is really needed. I was just trying to get the test box green... As long as it will be merged without that, it's better to not waste any resources running the test.

**Comment by smuzaffar** [comment]
+externals

rename of data files

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Pull request merged**
