### PR TITLE
Initial data files for tests of TriggerResults Raw data format

### PR DESCRIPTION
**Pull request by wddgit**
Initial data files for tests of TriggerResults Raw data format

### CODE REVIEW

**Comment by makortel** [comment]
@smuzaffar, what needs to be done to get this PR assigned to core?

**Comment by makortel** [comment]
+core

**Comment by wddgit** [comment]
please test

Not sure if I need to do this or not. It looks like it wants me to but there are no tests just data files.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
Merging and for next ib

**Pull request merged**
